### ISSUE TITLE
No tiffcrop ??

### ISSUE THREAD

**Issue by austin-cs** [waugustus/CarpetFuzz#3]
We would like to try tiffcp and tiffcrop, but "tiffcrop.1" is not found.
We download the "tiffcrop.1" from "archlinux" , https://archlinux.org/packages/extra/x86_64/libtiff/.
But your "generate_combination.py" cannot handle it well.

It seems to us that artifacts are not synchronized with paper you published in USENIX Security'23

**Comment by waugustus** [comment]
First of all, Thank you for your interest in this repository.

---

> We would like to try tiffcp and tiffcrop, but "tiffcrop.1" is not found.

I did mention **how to find the manage files** in the [USAGE](https://github.com/waugustus/CarpetFuzz/blob/main/README.md#usage) section, using `tiffcp` as an example. The file you're looking for, "tiffcrop.1", is located in the same directory as "tiffcp.1." I suggest taking the time to review the section with a calm and patient mindset."

```
# Step 2
# Use CarpetFuzz to analyze the relationships from the manpage file
# The manpage files are usually in the build directory (share/man/man1).
python3 ${CarpetFuzz}/scripts/find_relationship.py --file $PWD/build_carpetfuzz/share/man/man1/tiffcp.1
```

By the way, I noticed that libtiff no longer compiles manpages starting from version 4.5.0, or at least not temporarily. To obtain these manpages, you can roll back to version 4.4.0 or earlier.

---

> We download the "tiffcrop.1" from "archlinux" , https://archlinux.org/packages/extra/x86_64/libtiff/.
But your "generate_combination.py" cannot handle it well.

Since you're saying that the script cannot handle it, what exactly is the error? Without any detailed description, I don't think I can fix it. In my own attempts, the script works well with the **compiled** manpage.

---

>  It seems to us that artifacts are not synchronized with paper you published in USENIX Security'23

I'm curious, what makes you think that way? In fact, we will submit the artifact to the USENIX Security '23 artifact evaluation process, and by then we will have prepared all the deployment scripts for reproducing the experiments in the paper, which will be accessible in [CarpetFuzz-experiments](https://github.com/waugustus/CarpetFuzz-experiments).

**Comment by austin-cs** [comment]
Hi, Dawei:

我们想**重现你论文中的结果**;

但是, 以下原因:
1.原先以为, 论文中的manpages都会放在这github 内, 但只看到tiffcp.1;
2.依 USAGE section的指令下载 tiffcrop.1时, 又没有成功;
3.加上, [13579and2468]也发现 rank_combination.py 有问题;
4.另外, CarpetFuzz-experiments 也是空的, 没资料;(如附图所示)

使我觉得有这github的内容, 应该不完整,  无法产生论文中的相同结果;
第一时间通知你.

周三起, 我們會再試

<img width="923" alt="CarpetFuzz" src="https://user-images.githubusercontent.com/110702520/233905957-102f967b-fccd-4c86-bea0-fd3cc10742a1.PNG">

**Comment by waugustus** [comment]
Hi, thank you once again for your interest. Due to my recent busy schedule, my focus is currently on ensuring that users can use CarpetFuzz as intended. However, I plan to upload all the deployment scripts for reproducing the experiments in the paper to the [CarpetFuzz-experiments](https://github.com/waugustus/CarpetFuzz-experiments) repository before **June**. Stay tuned for further updates.

**Comment by waugustus** [comment]
Also, just to clarify, the tool available in this repository is the exact same one we used in the paper.
